name: Arctern-bot Release Doc

on:
  push:

jobs:
  compile-and-publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run bot realease
        run: |
          arctern_docs_released_branch=`cat version.json | jq -r .arctern_docs_released_branch` && \
          released_check_flag=`cat version.json | jq -r .released` && \
          docker build --tag arctern-docs:bot-release . --file ./docker/Dockerfile && \
          echo "------------------------------------------------------------- docker image build ok --------------------------------------" &&  \
          docker run -v ${GITHUB_WORKSPACE}:/arctern-docs arctern-docs:bot-release && \
          echo "------------------------------------------------------------- compile ok --------------------------------------"
